spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: catalog
    password: catalog
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        hibernate.jdbc.batch_size: 200
        hibernate.order_inserts: true
        hibernate.order_updates: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /v3/api-docs

management:
  endpoints.web.exposure.include: health,info